# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake-4.0.3-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake-4.0.3-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ollie/workspace/game-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ollie/workspace/game-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/cmake-4.0.3-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake-4.0.3-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ollie/workspace/game-engine/CMakeFiles /home/ollie/workspace/game-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ollie/workspace/game-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameEngine

# Build rule for target.
GameEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameEngine
.PHONY : GameEngine

# fast build rule for target.
GameEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/build
.PHONY : GameEngine/fast

include/glad.o: include/glad.c.o
.PHONY : include/glad.o

# target to build an object file
include/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/include/glad.c.o
.PHONY : include/glad.c.o

include/glad.i: include/glad.c.i
.PHONY : include/glad.i

# target to preprocess a source file
include/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/include/glad.c.i
.PHONY : include/glad.c.i

include/glad.s: include/glad.c.s
.PHONY : include/glad.s

# target to generate assembly for a file
include/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/include/glad.c.s
.PHONY : include/glad.c.s

src/core/Input.o: src/core/Input.cpp.o
.PHONY : src/core/Input.o

# target to build an object file
src/core/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Input.cpp.o
.PHONY : src/core/Input.cpp.o

src/core/Input.i: src/core/Input.cpp.i
.PHONY : src/core/Input.i

# target to preprocess a source file
src/core/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Input.cpp.i
.PHONY : src/core/Input.cpp.i

src/core/Input.s: src/core/Input.cpp.s
.PHONY : src/core/Input.s

# target to generate assembly for a file
src/core/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Input.cpp.s
.PHONY : src/core/Input.cpp.s

src/core/Renderer.o: src/core/Renderer.cpp.o
.PHONY : src/core/Renderer.o

# target to build an object file
src/core/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Renderer.cpp.o
.PHONY : src/core/Renderer.cpp.o

src/core/Renderer.i: src/core/Renderer.cpp.i
.PHONY : src/core/Renderer.i

# target to preprocess a source file
src/core/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Renderer.cpp.i
.PHONY : src/core/Renderer.cpp.i

src/core/Renderer.s: src/core/Renderer.cpp.s
.PHONY : src/core/Renderer.s

# target to generate assembly for a file
src/core/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Renderer.cpp.s
.PHONY : src/core/Renderer.cpp.s

src/core/ResourceManager.o: src/core/ResourceManager.cpp.o
.PHONY : src/core/ResourceManager.o

# target to build an object file
src/core/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/ResourceManager.cpp.o
.PHONY : src/core/ResourceManager.cpp.o

src/core/ResourceManager.i: src/core/ResourceManager.cpp.i
.PHONY : src/core/ResourceManager.i

# target to preprocess a source file
src/core/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/ResourceManager.cpp.i
.PHONY : src/core/ResourceManager.cpp.i

src/core/ResourceManager.s: src/core/ResourceManager.cpp.s
.PHONY : src/core/ResourceManager.s

# target to generate assembly for a file
src/core/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/ResourceManager.cpp.s
.PHONY : src/core/ResourceManager.cpp.s

src/core/Simplex.o: src/core/Simplex.cpp.o
.PHONY : src/core/Simplex.o

# target to build an object file
src/core/Simplex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Simplex.cpp.o
.PHONY : src/core/Simplex.cpp.o

src/core/Simplex.i: src/core/Simplex.cpp.i
.PHONY : src/core/Simplex.i

# target to preprocess a source file
src/core/Simplex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Simplex.cpp.i
.PHONY : src/core/Simplex.cpp.i

src/core/Simplex.s: src/core/Simplex.cpp.s
.PHONY : src/core/Simplex.s

# target to generate assembly for a file
src/core/Simplex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/Simplex.cpp.s
.PHONY : src/core/Simplex.cpp.s

src/core/VertexArray.o: src/core/VertexArray.cpp.o
.PHONY : src/core/VertexArray.o

# target to build an object file
src/core/VertexArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/VertexArray.cpp.o
.PHONY : src/core/VertexArray.cpp.o

src/core/VertexArray.i: src/core/VertexArray.cpp.i
.PHONY : src/core/VertexArray.i

# target to preprocess a source file
src/core/VertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/VertexArray.cpp.i
.PHONY : src/core/VertexArray.cpp.i

src/core/VertexArray.s: src/core/VertexArray.cpp.s
.PHONY : src/core/VertexArray.s

# target to generate assembly for a file
src/core/VertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/VertexArray.cpp.s
.PHONY : src/core/VertexArray.cpp.s

src/core/View.o: src/core/View.cpp.o
.PHONY : src/core/View.o

# target to build an object file
src/core/View.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/View.cpp.o
.PHONY : src/core/View.cpp.o

src/core/View.i: src/core/View.cpp.i
.PHONY : src/core/View.i

# target to preprocess a source file
src/core/View.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/View.cpp.i
.PHONY : src/core/View.cpp.i

src/core/View.s: src/core/View.cpp.s
.PHONY : src/core/View.s

# target to generate assembly for a file
src/core/View.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/core/View.cpp.s
.PHONY : src/core/View.cpp.s

src/graphics/Texture.o: src/graphics/Texture.cpp.o
.PHONY : src/graphics/Texture.o

# target to build an object file
src/graphics/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/Texture.cpp.o
.PHONY : src/graphics/Texture.cpp.o

src/graphics/Texture.i: src/graphics/Texture.cpp.i
.PHONY : src/graphics/Texture.i

# target to preprocess a source file
src/graphics/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/Texture.cpp.i
.PHONY : src/graphics/Texture.cpp.i

src/graphics/Texture.s: src/graphics/Texture.cpp.s
.PHONY : src/graphics/Texture.s

# target to generate assembly for a file
src/graphics/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/graphics/Texture.cpp.s
.PHONY : src/graphics/Texture.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GameEngine"
	@echo "... include/glad.o"
	@echo "... include/glad.i"
	@echo "... include/glad.s"
	@echo "... src/core/Input.o"
	@echo "... src/core/Input.i"
	@echo "... src/core/Input.s"
	@echo "... src/core/Renderer.o"
	@echo "... src/core/Renderer.i"
	@echo "... src/core/Renderer.s"
	@echo "... src/core/ResourceManager.o"
	@echo "... src/core/ResourceManager.i"
	@echo "... src/core/ResourceManager.s"
	@echo "... src/core/Simplex.o"
	@echo "... src/core/Simplex.i"
	@echo "... src/core/Simplex.s"
	@echo "... src/core/VertexArray.o"
	@echo "... src/core/VertexArray.i"
	@echo "... src/core/VertexArray.s"
	@echo "... src/core/View.o"
	@echo "... src/core/View.i"
	@echo "... src/core/View.s"
	@echo "... src/graphics/Texture.o"
	@echo "... src/graphics/Texture.i"
	@echo "... src/graphics/Texture.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

